version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
#    command: uvicorn app.api.server:app --proxy-headers --reload --workers 1 --host 0.0.0.0 --port 8000
    command: uvicorn api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/fastapi_template
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
